Добавлен базовый функционал для пользователей и предметов
Luz1634/java-shareit pull request #1
Opened 2024-01-16 22:59 UTC by Luz1634

2024-01-17 20:28 UTC, z8q requested changes

2024-01-17 20:28 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private List<Item> items;
Поле items можно убрать.
Когда появятся таблицы, мы сможем достать этот список из таблицы Item. В ней столбец owner, который будет содержать foreignKey от таблицы User - поле id.
Будет применяться JpaRepository и можно будет достать каким-то таким образом itemRepository.findByOwnerId(userId)
Таблица User не будет содержать foreign-ключей

2024-01-17 20:28 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserRequestUpdate.java
> +public class UserRequestUpdate {
Есть решение, как не разделять на отдельные дто для создания и обновления.
Через использование валидационных групп.
При желании, можно попробовать применить)
```
На английском, блок Using Validation Groups:
https://reflectoring.io/bean-validation-with-spring-boot/
На русском, блок Группы валидаций:
https://struchkov.dev/blog/ru/spring-boot-validation/
```
Стоит обратить внимание, что для корректной работы, над классом-контроллером нужно ставить `@Validated`

2024-01-17 20:28 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                             @Min(value = 1, message = "ItemId должно быть больше 0")
Для работы `@Min` нужно еще поставить `@Validated` над классом

2024-01-18 15:31 UTC, Luz1634 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private List<Item> items;
В следующем спринте уберу. Добавил поле только на этот спринт чтобы было проще вывести предметы для владельца

2024-01-18 20:03 UTC, z8q approved these changes

2024-01-24 20:38 UTC, merged