Добавлена аренда вещей и комментарии
Luz1634/java-shareit pull request #2
Opened 2024-01-29 03:02 UTC by Luz1634

2024-01-29 20:04 UTC, z8q requested changes

2024-01-29 20:04 UTC, z8q commented on src/main/resources/schema.sql
> +  CONSTRAINT pk_item PRIMARY KEY (id)
Для таблицы определен PRIMARY KEY – поле id.
Также есть поля, которые мы можем определить, как FOREIGN KEY – это owner_id и request_id.
Для создания связи между таблицами можно объявить constraint-ы в таком виде:
CONSTRAINT fk_item_on_owner FOREIGN KEY (owner_id) REFERENCES users (id)

Тогда в 14-й строке можно будет записать так:
owner_id BIGINT NOT NULL, – без REFERENCES

2024-01-29 20:04 UTC, z8q commented on src/main/resources/schema.sql
> +  CONSTRAINT pk_item PRIMARY KEY (id)
к таблицам ниже комментарий тоже применим

2024-01-29 20:04 UTC, z8q commented on src/main/resources/schema.sql
> +  status booking_status NOT NULL,
для статуса ниже тоже можно определить constraint:
CONSTRAINT fk_booking_status FOREIGN KEY (status) REFERENCES booking_status

Но на самом деле, если в модели будет определен enum, здесь в схеме не придется создавать отдельную табличку с booking_status

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private long id;
В работе приложения мы используем дто и модели.
Дто используются, чтобы определить правила валидации для входящих и исходящих объектов.
Плюс мы работаем с дто в логике приложения – сервисных классах.
Модели (Сущности хибернейта) используются, чтобы определить связи между объектами, индексы, правила загрузки зависимых полей (Eager, Lazy) и пр. Именно модели мы используем для сохранения в базу.
Сейчас в проекте, на примере Item, есть dto для запроса и ответа, есть модель и есть еще ItemDb. Предлагается объединить модель и ItemDb в один класс Item. Потому что сейчас разделение на модель и ItemDb только увеличивает количество маппингов.
Такой же подход стоит применить к остальным пакетам – user, booking

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User addUser(User user) {
Удается добавить дубликаты пользователей с одинаковыми именами и почтой

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User updateUser(User user) {
Удается обновить пользователя с пустыми полями:
patch http://localhost:8080/users/1
```JSON
{
	"name": "",
	"email": ""
}
```

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public Item updateItem(Item item, long userId) {
Удается обновить вещь с пустыми полями:
patch http://localhost:8080/items/1
```JSON
{
	"name": "",
	"description": "",
	"available": true
}
```
description может быть можно делать пустым, но имя стоит сделать обязательным полем

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public List<ItemControllerResponse> getOwnerItems(@Min(value = 1, message = "UserId должно быть больше 0")
По тз, при запросе get /items, владелец видит даты последнего и ближайшего следующего бронирования для каждой вещи.
Сейчас возвращаются только id бронирования и арендатора:
```JSON
"lastBooking": {
   "id": 1,
   "bookerId": 2
}
```

2024-01-29 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<ItemDb> search(String text);
Если к аргументу добавить аннотацию Param, то в query можно будет вместо ?1 писать так:
concat('%', :text, '%')

Сам метод такой:
List search(`@Param`("text") String text);

2024-02-02 03:12 UTC, Luz1634 commented on src/main/resources/schema.sql
> +  status booking_status NOT NULL,
Я попробовал работу без объявления статуса в базе данных, но решил для себя оставить в таком виде. Добавить constraint для enum у меня не получилось

2024-02-02 03:19 UTC, Luz1634 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User addUser(User user) {
Я не совсем понимаю почему, но при включенной настройке профилей в файле application.properties не применяются настройки для hibernate и не работает условие на уникальность емейлов. Без это настройки дубликаты не создаются

2024-02-02 23:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User addUser(User user) {
Настройка
spring.config.activate.on-profile=ci,test
применяется ко всему файлу.
Чтобы все  property работали, нужно запускать приложение с указанием какого-нибудь профиля, например ci.
Профиль указывается в Modify Run Configuration
<img width="417" alt="Screenshot 2024-02-03 at 03 00 31" src="https://github.com/Luz1634/java-shareit/assets/77640736/b96fde70-5621-42ec-8bef-9ce5aafd8c6d">

без указания профиля при запуске не срабатывает вот эта настройка:
spring.jpa.hibernate.ddl-auto=none
И hibernate создает таблицы исходя из данных Entity-моделей, а не по schema.sql,
поэтому constraint-ы не применяются

2024-02-02 23:16 UTC, z8q approved these changes

2024-02-03 14:51 UTC, merged