Добавлен функционал запроса вещей
Luz1634/java-shareit pull request #3
Opened 2024-02-05 17:56 UTC by Luz1634

2024-02-06 18:29 UTC, z8q requested changes

2024-02-06 18:29 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Pageable sortedByStart = PageRequest.of(from / size, size);
Название переменной как в bookingService, но здесь способ сортировки не указывается. Возможно стоит переименовать)

2024-02-06 18:29 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +class BookingRepositoryTest {
В тестах, которые помечены `@DataJpaTest`,  стоит что-то сделать с пустыми тестами.
Корректную работу методов можно зафиксировать, особенно с длинными названиями

2024-02-07 01:18 UTC, Luz1634 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Первоначально добавил их для проверки правильности написания запросных методов. Сейчас посмотрел что достаточно одного теста с @DataJpaTest для этой проверки. Добавил вариантов теста для метода поиска по названию и описанию, и пару тестов для методов с большими названиями

2024-02-07 18:49 UTC, z8q approved these changes

2024-02-08 18:01 UTC, merged